In [1]:
import tensorflow as tf

In [2]:
a = tf.constant([5])
b = tf.constant([3])

In [3]:
c = tf.add(a,b)

In [6]:
session = tf.Session()

In [7]:
result = session.run(c)

In [9]:
print(result)

[8]


In [11]:
tensor = tf.constant([ [[1,2,3],[2,3,5],[4,6,7] ] , [[3,4,5],[5,6,7],[3,5,4]] , [[5,6,8],[2,7,8],[6,7,9]] ])

In [14]:
with tf.Session() as session:
    result = session.run(tensor)
    print("The tensor(3*3*3) is : \n %s \n" %result)

The tensor(3*3*3) is : 
 [[[1 2 3]
  [2 3 5]
  [4 6 7]]

 [[3 4 5]
  [5 6 7]
  [3 5 4]]

 [[5 6 8]
  [2 7 8]
  [6 7 9]]] 



In [23]:
matrix_one = tf.constant([[1,2],[5,6]])
matrix_two = tf.constant([[3,4],[7,8]])


In [24]:
product = tf.matmul(matrix_one,matrix_two)

In [25]:
with tf.Session() as session:
    result = session.run(product)
    print("The product is:\n")
    print(result)

The product is:

[[17 20]
 [57 68]]


In [34]:
state = tf.Variable(0)

In [36]:
one = tf.constant(1)
new_value = tf.add(state, one)
update = tf.assign(state, new_value)

In [37]:
init_op = tf.global_variables_initializer()

In [43]:
with tf.Session() as session:
    session.run(init_op)
    print(session.run(state))
    for _ in range(3):
     session.run(update)
    print(session.run(state))

0
3


In [45]:
a = tf.placeholder(tf.float32)
b = a*2

In [47]:
with tf.Session() as session:
    result = session.run(b,feed_dict = {a:3.5})
    print(result)

7.0


In [50]:
a = tf.placeholder(tf.int32)
b = a*2
dictionary = {a:[ [[1,2,3],[2,3,5],[4,6,7] ] , [[3,4,5],[5,6,7],[3,5,4]] , [[5,6,8],[2,7,8],[6,7,9]] ]}
with tf.Session() as session:
    result = session.run(b,feed_dict = dictionary )
    print(result)

[[[ 2  4  6]
  [ 4  6 10]
  [ 8 12 14]]

 [[ 6  8 10]
  [10 12 14]
  [ 6 10  8]]

 [[10 12 16]
  [ 4 14 16]
  [12 14 18]]]
